# Default conf.d server for proxying API
upstream api_upstream {
  server api:3000;
}

server {
  listen 80 default_server;
  server_name localhost;

  # Page de statut Nginx
  location /nginx-status {
    stub_status on;
  }
  # API routes (with and without /api prefix)
  location /api/ {
    proxy_pass http://api_upstream/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location / {
    proxy_pass http://api_upstream/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
